import React,{useEffect,useRef,useState,type ChangeEvent}from'react';

type Props={token:string;deviceId:string};
type ServerMessage={type:string;payload?:any};
function bytesToB64(bytes:Uint8Array){let raw='';for(let i=0;i<bytes.length;i++)raw+=String.fromCharCode(bytes[i]);return btoa(raw)}
function b64ToText(value:string){const raw=atob(value);const bytes=Uint8Array.from(raw,c=>c.charCodeAt(0));return new TextDecoder().decode(bytes)}
function wsUrl(){const scheme=location.protocol==='https:'?'wss:':'ws:';return `${scheme}//${location.host}/v1/streams/ws`}

export default function LiveTerminal({token,deviceId}:Props){
 const[program,setProgram]=useState('powershell.exe');const[cwd,setCwd]=useState('C:\\projects');const[args,setArgs]=useState('[]');const[input,setInput]=useState('');const[output,setOutput]=useState('');const[status,setStatus]=useState('disconnected');const[ptyId,setPtyId]=useState('');
 const ws=useRef<WebSocket|null>(null);const seq=useRef(0);const pendingInput=useRef<Map<number,string>>(new Map());const eofRef=useRef(false);const ping=useRef<number|undefined>(undefined);const reconnectTimer=useRef<number|undefined>(undefined);const intentionalClose=useRef(false);const relayId=useRef('');const resumeToken=useRef('');const lastOutputSeq=useRef<number|undefined>(undefined);const requestRef=useRef<any>(null);
 useEffect(()=>()=>hardDisconnect('component_unmount'),[]);
 function append(text:string){setOutput(v=>(v+text).slice(-500_000))}
 function clearTimers(){if(ping.current!==undefined)window.clearInterval(ping.current);if(reconnectTimer.current!==undefined)window.clearTimeout(reconnectTimer.current);ping.current=undefined;reconnectTimer.current=undefined}
 function hardDisconnect(reason='browser_close'){intentionalClose.current=true;clearTimers();const socket=ws.current;ws.current=null;if(socket&&socket.readyState===WebSocket.OPEN){socket.send(JSON.stringify({type:'close',payload:{reason}}));socket.close()}relayId.current='';resumeToken.current='';lastOutputSeq.current=undefined;requestRef.current=null;pendingInput.current.clear();seq.current=0;eofRef.current=false;setStatus('disconnected')}
 function buildRequest(){let parsedArgs:string[]=[];try{parsedArgs=JSON.parse(args);if(!Array.isArray(parsedArgs)||parsedArgs.some(v=>typeof v!=='string'))throw new Error('args')}catch{throw new Error('args must be a JSON string array')}return{kind:'terminal',direction:'bidirectional',resource_id:'new',metadata:{program,cwd,args_json:JSON.stringify(parsedArgs),env_json:'{}',rows:'30',cols:'120'}}}
 function connect(resume=false){clearTimers();intentionalClose.current=false;if(!token||!deviceId){setStatus('token and device required');return}let request:any;try{request=resume&&requestRef.current?requestRef.current:buildRequest()}catch(e){setStatus((e as Error).message);return}if(!resume){relayId.current='';resumeToken.current='';lastOutputSeq.current=undefined;pendingInput.current.clear();seq.current=0;eofRef.current=false;setPtyId('');setOutput('');requestRef.current=request}const socket=new WebSocket(wsUrl());ws.current=socket;setStatus(resume?'resuming':'connecting');socket.onopen=()=>{setStatus(resume?'resuming':'authorizing');const resumePayload=resume&&relayId.current&&resumeToken.current?{relay_id:relayId.current,resume_token:resumeToken.current,last_output_seq:lastOutputSeq.current}:null;socket.send(JSON.stringify({type:'hello',payload:{token,device_id:deviceId,request,resume:resumePayload}}));ping.current=window.setInterval(()=>{if(socket.readyState===WebSocket.OPEN)socket.send(JSON.stringify({type:'ping',payload:{timestamp_unix_ms:Date.now()}}))},5000)};socket.onmessage=e=>{let m:ServerMessage;try{m=JSON.parse(String(e.data))}catch{return}const p=m.payload||{};if(m.type==='opened'){if(p.ok){setStatus(p.resumed?'resumed':'connected');setPtyId(p.resource_id||ptyId);relayId.current=p.relay_id||relayId.current;resumeToken.current=p.resume_token||resumeToken.current;const next=Number.isFinite(p.next_input_seq)?Number(p.next_input_seq):seq.current;for(const key of Array.from(pendingInput.current.keys()))if(key<next)pendingInput.current.delete(key);seq.current=next;if(p.resumed){const resend=Array.from(pendingInput.current.entries()).filter(([n])=>n>=next).sort((a,b)=>a[0]-b[0]);for(const[n,payload]of resend){if(n!==seq.current)break;socket.send(JSON.stringify({type:'input',payload:{frame:{seq:n,eof:false,payload_base64:payload}}}));seq.current++}}}else{setStatus(`open failed: ${p.error||'unknown'}`)}}else if(m.type==='input_ack'){const next=Number(p.next_input_seq||0);for(const key of Array.from(pendingInput.current.keys()))if(key<next)pendingInput.current.delete(key);if(next>seq.current)seq.current=next}else if(m.type==='output'){const f=p.frame||{};if(typeof f.seq==='number')lastOutputSeq.current=f.seq;try{append(b64ToText(f.payload_base64||''))}catch{}if(f.eof){eofRef.current=true;setStatus('eof')}}else if(m.type==='closed'){eofRef.current=true;setStatus(`closed${p.reason?`: ${p.reason}`:''}`);resumeToken.current=''}else if(m.type==='error'){setStatus(`error: ${p.message||'unknown'}`)}};socket.onerror=()=>setStatus(resume?'resume websocket error':'websocket error');socket.onclose=()=>{if(ping.current!==undefined)window.clearInterval(ping.current);ping.current=undefined;if(ws.current===socket)ws.current=null;if(intentionalClose.current||eofRef.current)return;if(resumeToken.current&&relayId.current){setStatus('connection lost · resuming');reconnectTimer.current=window.setTimeout(()=>connect(true),1000)}else setStatus('disconnected')}}
 function send(){const socket=ws.current;if(!socket||socket.readyState!==WebSocket.OPEN||!input)return;const bytes=new TextEncoder().encode(input);if(bytes.length>256*1024){setStatus('input exceeds 256 KiB');return}const payload=bytesToB64(bytes);const frameSeq=seq.current++;pendingInput.current.set(frameSeq,payload);socket.send(JSON.stringify({type:'input',payload:{frame:{seq:frameSeq,eof:false,payload_base64:payload}}}));setInput('')}
 return <div className="card liveTerminal"><div className="sectionHead"><div><p>LIVE STREAM</p><h3>Remote PTY / ConPTY</h3></div><span className="streamStatus">{status}</span></div><div className="streamFields"><label><span>Program</span><input value={program} onChange={(e:ChangeEvent<HTMLInputElement>)=>setProgram(e.target.value)}/></label><label><span>Workspace cwd</span><input value={cwd} onChange={(e:ChangeEvent<HTMLInputElement>)=>setCwd(e.target.value)}/></label><label><span>Args JSON</span><input value={args} onChange={(e:ChangeEvent<HTMLInputElement>)=>setArgs(e.target.value)}/></label></div><div className="actions"><button onClick={()=>connect(false)} disabled={!token||!deviceId||status==='connecting'||status==='authorizing'}>Open live terminal</button><button className="ghost" onClick={()=>hardDisconnect()} disabled={!ws.current&&!resumeToken.current}>Close</button>{ptyId&&<code>{ptyId}</code>}</div><pre className="terminalOutput">{output||'No terminal output yet.'}</pre><div className="terminalInput"><textarea rows={3} value={input} onChange={(e:ChangeEvent<HTMLTextAreaElement>)=>setInput(e.target.value)} placeholder={'Type input, e.g. php -v\n'}/><button onClick={send} disabled={!['connected','resumed'].includes(status)||!input}>Send</button></div><small>Unexpected browser/socket loss keeps the relay alive briefly. VSN rotates the resume token, replays bounded missed output, and advertises the Agent-processed next input sequence and replays any unacknowledged terminal input before accepting new input.</small></div>
}
