import React,{useRef,useState,type ChangeEvent}from'react';

type Props={token:string;deviceId:string};type Msg={type:string;payload?:any};
function wsUrl(){const scheme=location.protocol==='https:'?'wss:':'ws:';return `${scheme}//${location.host}/v1/streams/ws`}
function b64ToBytes(value:string){const raw=atob(value);return Uint8Array.from(raw,c=>c.charCodeAt(0))}
const MAX_RESULT_BYTES=16*1024*1024;
export default function LiveDatabase({token,deviceId}:Props){
 const[path,setPath]=useState('C:\\projects\\app\\database.sqlite');const[operation,setOperation]=useState<'browse'|'query'>('browse');const[entity,setEntity]=useState('users');const[sql,setSql]=useState('SELECT * FROM users LIMIT 100');const[status,setStatus]=useState('idle');const[result,setResult]=useState('');const socketRef=useRef<WebSocket|null>(null);
 function close(){const s=socketRef.current;socketRef.current=null;if(s&&s.readyState===WebSocket.OPEN)s.close()}
 function run(){if(!token||!deviceId||!path){setStatus('token/device/path required');return}if(operation==='query'&&(!sql.trim()||sql.length>1024)){setStatus('query must be 1..1024 characters');return}close();setResult('');setStatus('connecting');const chunks:Uint8Array[]=[];let total=0;const socket=new WebSocket(wsUrl());socketRef.current=socket;socket.onopen=()=>{const metadata=operation==='browse'?{operation:'browse',entity,limit:'100',offset:'0'}:{operation:'query',sql};socket.send(JSON.stringify({type:'hello',payload:{token,device_id:deviceId,request:{kind:'database',direction:'agent_to_client',resource_id:path,metadata},resume:null}}));setStatus('authorizing')};socket.onmessage=e=>{let m:Msg;try{m=JSON.parse(String(e.data))}catch{return}const p=m.payload||{};if(m.type==='opened'){if(p.ok)setStatus('reading');else setStatus(`open failed: ${p.error||'unknown'}`)}else if(m.type==='output'){const bytes=b64ToBytes(p.frame?.payload_base64||'');total+=bytes.length;if(total>MAX_RESULT_BYTES){setStatus('result exceeded 16 MiB browser safety cap');socket.close();return}chunks.push(bytes);if(p.frame?.eof){const merged=new Uint8Array(total);let offset=0;for(const chunk of chunks){merged.set(chunk,offset);offset+=chunk.length}try{const parsed=JSON.parse(new TextDecoder().decode(merged));setResult(JSON.stringify(parsed,null,2));setStatus(`complete · ${total} bytes`)}catch{setResult(new TextDecoder().decode(merged));setStatus('complete · non-JSON payload')}}}else if(m.type==='error'){setStatus(`error: ${p.message||'unknown'}`)}else if(m.type==='closed'&&status==='reading'){setStatus('closed')}};socket.onerror=()=>setStatus('websocket error');socket.onclose=()=>{socketRef.current=null}}
 return <div className="card"><div className="sectionHead"><div><p>LIVE DATABASE</p><h3>Workspace SQLite read stream</h3></div><span className="streamStatus">{status}</span></div><label><span>Absolute SQLite path inside an Agent workspace</span><input value={path} onChange={(e:ChangeEvent<HTMLInputElement>)=>setPath(e.target.value)}/></label><div className="actions"><button className={operation==='browse'?'':'ghost'} onClick={()=>setOperation('browse')}>Browse</button><button className={operation==='query'?'':'ghost'} onClick={()=>setOperation('query')}>Read query</button></div>{operation==='browse'?<label><span>Entity/table</span><input value={entity} onChange={(e:ChangeEvent<HTMLInputElement>)=>setEntity(e.target.value)}/></label>:<label><span>Read-only SQL · max 1024 chars</span><textarea rows={5} value={sql} onChange={(e:ChangeEvent<HTMLTextAreaElement>)=>setSql(e.target.value)}/></label>}<div className="actions"><button onClick={run} disabled={!token||!deviceId}>Run live DB stream</button><button className="ghost" onClick={close} disabled={!socketRef.current}>Stop</button></div><pre className="terminalOutput">{result||'No database result yet.'}</pre><small>This 0.12 relay intentionally supports workspace-contained SQLite read operations only. External database credentials and mutation transactions are not exposed through the generic live stream.</small></div>
}
