import React,{useEffect,useRef,useState,type ChangeEvent}from'react';

type Props={token:string;deviceId:string};type Msg={type:string;payload?:any};type Mode='upload'|'download'|null;
const CHUNK=192*1024,MAX_MEMORY_FILE=256*1024*1024,MAX_REMOTE_FILE=8*1024*1024*1024;
function wsUrl(){const scheme=location.protocol==='https:'?'wss:':'ws:';return `${scheme}//${location.host}/v1/streams/ws`}
function bytesToB64(bytes:Uint8Array){let raw='';for(let i=0;i<bytes.length;i++)raw+=String.fromCharCode(bytes[i]);return btoa(raw)}
function b64ToBytes(value:string){const raw=atob(value);return Uint8Array.from(raw,c=>c.charCodeAt(0))}
function bytesToArrayBuffer(bytes:Uint8Array):ArrayBuffer{const out=new ArrayBuffer(bytes.byteLength);new Uint8Array(out).set(bytes);return out}
function hex(bytes:ArrayBuffer){return Array.from(new Uint8Array(bytes)).map(v=>v.toString(16).padStart(2,'0')).join('')}
function sleep(ms:number){return new Promise(r=>setTimeout(r,ms))}

export default function LiveFileTransfer({token,deviceId}:Props){
 const[remotePath,setRemotePath]=useState('C:\\projects\\artifact.bin');const[file,setFile]=useState<File|null>(null);const[status,setStatus]=useState('idle');const[progress,setProgress]=useState(0);const[detail,setDetail]=useState('');
 const socketRef=useRef<WebSocket|null>(null),modeRef=useRef<Mode>(null),requestRef=useRef<any>(null),relayId=useRef(''),resumeToken=useRef(''),lastOutputSeq=useRef<number|undefined>(undefined),reconnectTimer=useRef<number|undefined>(undefined),intentional=useRef(false),complete=useRef(false),fileRef=useRef<File|null>(null),downloadChunks=useRef<Uint8Array[]>([]),downloadBytes=useRef(0),uploadSha=useRef(''),downloadWriter=useRef<any>(null),uploadDigest=useRef('');
 useEffect(()=>()=>hardClose('component_unmount'),[]);
 function clearTimer(){if(reconnectTimer.current!==undefined)window.clearTimeout(reconnectTimer.current);reconnectTimer.current=undefined}
 function resetRelay(){relayId.current='';resumeToken.current='';lastOutputSeq.current=undefined;requestRef.current=null;complete.current=false}
 function hardClose(reason='browser_close'){intentional.current=true;clearTimer();const s=socketRef.current;socketRef.current=null;if(s&&s.readyState===WebSocket.OPEN){s.send(JSON.stringify({type:'close',payload:{reason}}));s.close()}const writer=downloadWriter.current;downloadWriter.current=null;if(writer&&typeof writer.abort==='function'){void writer.abort().catch(()=>{})}modeRef.current=null;resetRelay();setStatus('idle')}
 function scheduleResume(){if(intentional.current||complete.current||!resumeToken.current||!relayId.current||!modeRef.current)return;setStatus('connection lost · resuming');clearTimer();reconnectTimer.current=window.setTimeout(()=>connect(true),1000)}
 async function startUpload(){if(!token||!deviceId||!file||!remotePath){setStatus('missing token/device/file/path');return}if(file.size>MAX_REMOTE_FILE){setStatus('remote file exceeds 8 GiB safety ceiling');return}hardClose();intentional.current=false;modeRef.current='upload';fileRef.current=file;uploadDigest.current='';setProgress(0);uploadSha.current='';if(file.size<=MAX_MEMORY_FILE){setDetail('hashing');uploadSha.current=hex(await crypto.subtle.digest('SHA-256',await file.arrayBuffer()))}else setDetail('large-file streaming mode · Agent computes final SHA-256');const transferId=`web-${Date.now()}-${Math.random().toString(16).slice(2)}`;const metadata:any={transfer_id:transferId,offset:'0'};if(uploadSha.current)metadata.expected_sha256=uploadSha.current;requestRef.current={kind:'file_upload',direction:'client_to_agent',resource_id:remotePath,metadata};connect(false)}
 async function startDownload(){if(!token||!deviceId||!remotePath){setStatus('missing token/device/path');return}hardClose();intentional.current=false;modeRef.current='download';downloadChunks.current=[];downloadBytes.current=0;downloadWriter.current=null;setProgress(0);setDetail('');const picker=(window as any).showSaveFilePicker;if(typeof picker==='function'){try{const handle=await picker({suggestedName:remotePath.split(/[\\/]/).pop()||'download.bin'});downloadWriter.current=await handle.createWritable();setDetail('streaming directly to disk')}catch(e:any){if(e?.name==='AbortError'){setStatus('download cancelled');modeRef.current=null;return}setDetail('direct-to-disk unavailable; using bounded memory fallback')}}requestRef.current={kind:'file_download',direction:'agent_to_client',resource_id:remotePath,metadata:{offset:'0'}};connect(false)}
 function connect(resume:boolean){clearTimer();const mode=modeRef.current,request=requestRef.current;if(!mode||!request||!token||!deviceId)return;const socket=new WebSocket(wsUrl());socketRef.current=socket;setStatus(resume?'resuming':mode==='upload'?'authorizing upload':'authorizing download');socket.onopen=()=>{const resumePayload=resume&&relayId.current&&resumeToken.current?{relay_id:relayId.current,resume_token:resumeToken.current,last_output_seq:lastOutputSeq.current}:null;socket.send(JSON.stringify({type:'hello',payload:{token,device_id:deviceId,request,resume:resumePayload}}))};socket.onmessage=async e=>{let m:Msg;try{m=JSON.parse(String(e.data))}catch{return}const p=m.payload||{};if(m.type==='opened'){if(!p.ok){setStatus(`open failed: ${p.error||'unknown'}`);return}relayId.current=p.relay_id||relayId.current;resumeToken.current=p.resume_token||resumeToken.current;if(mode==='upload'){setStatus(p.resumed?'upload resumed':'uploading');const next=Number.isFinite(p.next_input_seq)?Number(p.next_input_seq):0;void pumpUpload(socket,next)}else setStatus(p.resumed?'download resumed':'downloading')}else if(m.type==='input_ack'&&mode==='upload'){const committed=Number(p.committed_bytes||0);if(typeof p.digest_sha256==='string'&&p.digest_sha256){uploadDigest.current=p.digest_sha256;setDetail(`Agent SHA-256 ${p.digest_sha256}`)}else if(Number.isFinite(committed)){const f=fileRef.current;setDetail(`Agent committed ${committed} bytes`);if(f&&f.size>0)setProgress(Math.min(100,Math.round(committed/f.size*100)))}}else if(m.type==='output'&&mode==='download'){const f=p.frame||{};if(typeof f.seq==='number')lastOutputSeq.current=f.seq;const bytes=b64ToBytes(f.payload_base64||'');downloadBytes.current+=bytes.length;if(downloadBytes.current>MAX_REMOTE_FILE){setStatus('download exceeded 8 GiB safety ceiling');intentional.current=true;socket.close();return}if(downloadWriter.current){if(bytes.length)await downloadWriter.current.write(bytes)}else{if(downloadBytes.current>MAX_MEMORY_FILE){setStatus('memory fallback exceeded 256 MiB; use a browser with File System Access API');intentional.current=true;socket.close();return}downloadChunks.current.push(bytes)}setDetail(`${downloadBytes.current} bytes received${downloadWriter.current?' · direct-to-disk':''}`);if(f.eof)await finishDownload()}else if(m.type==='closed'){if(mode==='upload'&&p.reason==='upload_complete'){complete.current=true;setStatus('uploaded + SHA-256 finalized');setProgress(100);setDetail(uploadDigest.current?`Agent committed SHA-256 ${uploadDigest.current}`:'Agent committed and finalized the full file')}else if(!complete.current)setDetail(p.reason||'closed');resumeToken.current=''}else if(m.type==='error'){setStatus(`error: ${p.message||'unknown'}`)}};socket.onerror=()=>setStatus(resume?'resume websocket error':'websocket error');socket.onclose=()=>{if(socketRef.current===socket)socketRef.current=null;scheduleResume()}}
 async function pumpUpload(socket:WebSocket,nextSeq:number){const f=fileRef.current;if(!f)return;let seq=nextSeq,offset=Math.min(f.size,nextSeq*CHUNK);if(f.size===0&&nextSeq===0){socket.send(JSON.stringify({type:'input',payload:{frame:{seq:0,eof:true,payload_base64:''}}}));return}while(offset<f.size&&socket.readyState===WebSocket.OPEN&&!intentional.current){while(socket.bufferedAmount>1024*1024&&socket.readyState===WebSocket.OPEN)await sleep(20);if(socket.readyState!==WebSocket.OPEN)return;const end=Math.min(f.size,offset+CHUNK);const bytes=new Uint8Array(await f.slice(offset,end).arrayBuffer());socket.send(JSON.stringify({type:'input',payload:{frame:{seq:seq++,eof:end===f.size,payload_base64:bytesToB64(bytes)}}}));offset=end;setProgress(Math.max(1,Math.round(offset/f.size*100)));}}
 async function finishDownload(){if(downloadWriter.current){await downloadWriter.current.close();downloadWriter.current=null}else{const blob=new Blob(downloadChunks.current.map(bytesToArrayBuffer),{type:'application/octet-stream'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=remotePath.split(/[\\/]/).pop()||'download.bin';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}complete.current=true;setProgress(100);setStatus('downloaded');setDetail(`${downloadBytes.current} bytes downloaded`)}
 return <div className="card"><div className="sectionHead"><div><p>LIVE FILES</p><h3>Resumable upload / download</h3></div><span className="streamStatus">{status}</span></div><label><span>Workspace-contained remote path</span><input value={remotePath} onChange={(e:ChangeEvent<HTMLInputElement>)=>setRemotePath(e.target.value)}/></label><label><span>Local file for upload</span><input type="file" onChange={(e:ChangeEvent<HTMLInputElement>)=>setFile(e.target.files?.[0]||null)}/></label><div className="actions"><button onClick={()=>void startUpload()} disabled={!file||!token||!deviceId}>Upload + SHA-256 verify</button><button className="ghost" onClick={()=>void startDownload()} disabled={!token||!deviceId}>Download</button><button className="ghost" onClick={()=>hardClose()} disabled={!socketRef.current&&!resumeToken.current}>Stop</button></div><div className="progress"><div style={{width:`${progress}%`}}/></div><small>{detail||'Unexpected socket loss resumes within the relay window. Upload restarts at the Agent-acknowledged fixed-chunk sequence; download replays only output after the last browser-confirmed sequence. Large downloads stream directly to disk when File System Access API is available; memory fallback remains capped at 256 MiB. Uploads stream up to the Agent\'s 8 GiB workspace ceiling, with final SHA-256 computed by the Agent.'}</small></div>
}
