# VSN dependency-quality policy.
# License certification remains a separate governed exercise; this file currently
# enforces dependency source hygiene, wildcard bans, and advisory visibility.

[graph]
all-features = true
targets = [
  "x86_64-unknown-linux-gnu",
  "aarch64-unknown-linux-gnu",
  "x86_64-apple-darwin",
  "aarch64-apple-darwin",
  "x86_64-pc-windows-msvc",
]

[advisories]
yanked = "warn"
unmaintained = "workspace"
unsound = "all"
ignore = []

[bans]
multiple-versions = "warn"
wildcards = "deny"
highlight = "simplest-path"
deny = []
skip = []
skip-tree = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
