export type AgentCommand =
  | 'status' | 'machine' | 'security.status' | 'audit.verify' | 'config.show'
  | 'process.list' | 'process.metrics' | 'process.managed.status' | 'process.managed.start' | 'process.managed.stop'
  | 'port.list' | 'port.check' | 'service.status' | 'service.action' | 'health.tcp' | 'log.tail'
  | 'runtime.list' | 'runtime.registry' | 'runtime.audit' | 'runtime.repair' | 'runtime.catalog' | 'runtime.install' | 'runtime.activate' | 'runtime.uninstall'
  | 'container.backends' | 'container.list' | 'container.action' | 'container.compose' | 'container.registry-publish'
  | 'project.detect' | 'project.dependencies' | 'project.bootstrap-plan' | 'project.bootstrap'
  | 'workspace.roots' | 'workspace.add' | 'workspace.remove'
  | 'files.list' | 'files.read' | 'files.write' | 'files.binary.status' | 'files.digest' | 'files.mkdir' | 'files.move' | 'files.delete' | 'terminal.exec' | 'terminal.session.start' | 'terminal.session.write' | 'terminal.session.read' | 'terminal.session.read-wait' | 'terminal.session.status' | 'terminal.session.stop' | 'terminal.session.remove' | 'terminal.session.list' | 'terminal.pty.start' | 'terminal.pty.write' | 'terminal.pty.read' | 'terminal.pty.read-wait' | 'terminal.pty.resize' | 'terminal.pty.status' | 'terminal.pty.stop' | 'terminal.pty.remove' | 'terminal.pty.list' | 'terminal.pty.scrollback.list' | 'terminal.pty.scrollback.read' | 'terminal.pty.scrollback.remove' | 'preview.fetch' | 'preview.request'
  | 'domain.plan'
  | 'database.workspace' | 'database.ui-demo' | 'database.model.analyze' | 'database.sqlite.inspect' | 'database.sqlite.query' | 'database.sqlite.browse' | 'database.sqlite.indexes' | 'database.sqlite.relations' | 'database.sqlite.stats' | 'database.sqlite.insert' | 'database.sqlite.update' | 'database.sqlite.delete'
  | 'database.native.postgres.job.start' | 'database.native.postgres.job.status' | 'database.native.postgres.job.list' | 'database.native.postgres.job.cancel' | 'database.native.postgres.txn.start' | 'database.native.postgres.txn.query' | 'database.native.postgres.txn.status' | 'database.native.postgres.txn.close' | 'database.cli.detect' | 'database.cli.inspect' | 'database.cli.query' | 'database.cli.job.start' | 'database.cli.job.status' | 'database.cli.job.list' | 'database.cli.job.cancel' | 'database.cli.job.output' | 'database.cli.job.output-remove' | 'database.tls.postgres.inspect' | 'database.tls.postgres.browse' | 'database.tls.postgres.query' | 'database.tls.mysql.inspect' | 'database.tls.mysql.browse' | 'database.tls.mysql.query' | 'database.native.mongo.inspect' | 'database.native.mongo.browse' | 'database.native.mongo.indexes' | 'database.native.mongo.stats' | 'database.native.mongo.insert' | 'database.native.mongo.update' | 'database.native.mongo.delete' | 'database.native.postgres.inspect' | 'database.native.postgres.browse' | 'database.native.postgres.query' | 'database.native.postgres.indexes' | 'database.native.postgres.relations' | 'database.native.postgres.stats' | 'database.native.postgres.insert' | 'database.native.postgres.update' | 'database.native.postgres.delete' | 'database.native.mysql.inspect' | 'database.native.mysql.browse' | 'database.native.mysql.query' | 'database.native.mysql.indexes' | 'database.native.mysql.relations' | 'database.native.mysql.stats' | 'database.native.mysql.insert' | 'database.native.mysql.update' | 'database.native.mysql.delete' | 'database.native.redis.inspect' | 'database.native.redis.get' | 'database.native.redis.set' | 'database.native.redis.delete'
  | 'vault.list' | 'vault.set' | 'vault.delete'
  | 'remote.status' | 'remote.configure' | 'remote.enroll';
export interface RuntimeDetection { id:string; installed:boolean; executable?:string; version?:string; }
export interface ProcessInfo { pid:number; name:string; command?:string; }
export interface ContainerBackend { id:string; installed:boolean; version?:string; daemon_reachable?:boolean; }
export interface MachineIdentity { device_id:string; display_name:string; os:string; public_key:string; created_at_unix:number; }
export interface RemoteConfig { enabled:boolean; control_plane_url?:string; control_plane_public_key?:string; poll_interval_ms:number; allow_remote_terminal:boolean; allow_remote_file_write:boolean; allow_remote_database_query:boolean; allow_remote_preview_interactive:boolean; }
export interface FileEntry { name:string; path:string; is_dir:boolean; size:number; modified_unix?:number; }
export interface DbClient { engine:string; executable?:string; version?:string; available:boolean; }
