[package]
name = "vsn-audit"
version = "0.38.1"
edition = "2021"
license = "Proprietary"

[dependencies]
fs2 = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
thiserror = "2"
uuid = { version = "1", features = ["v4"] }
vsn-security = { path = "../vsn-security" }
